app.eureka-server: localhost

server:
  port: 7000
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  application:
    name: product-service
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: products
      auto-index-creation: true

cache:
  config:
    entryTtl: 60

logging:
  level:
    root: INFO
    org.springframework.cache: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
app.eureka-server: eureka
spring.data.redis.host: redis
spring.data.mongodb.host: mongodb