services:
  eureka:
    build: eureka-service
    mem_limit: 512m
    ports:
      - "8761:8761"

  datetime-composite:
    build: datetime-composite-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  datetime:
    build: datetime-service
    mem_limit: 512m
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      mode: replicated
      replicas: 1
