services:

  client:
    build: client-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  dummy:
    build: dummy-service
    mem_limit: 512m
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
