server.port: 8081

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

---
spring.config.activate.on-profile: docker
server.port: 8081

